name: Renovate
on:
  # Allows manual/automated ad-hoc trigger
  workflow_dispatch:
  # schedule:
  #   # The "*" (#42, asterisk) character has special semantics in YAML, so this
  #   # string has to be quoted.
  #   - cron: '0/15 * * * *'
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.1
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
